# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 12:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('palakkad', django.db.models.manager.Manager()),
            ],
        ),
    ]
